#!/usr/bin/env python3
"""Generate LOSAT/src/stats/protein_tables.rs from NCBI's blast_stat.c (Session S08+).

NCBI's gapped Karlin-Altschul and Gumbel tables of the protein matrices (the `*_values`
arrays, 11 columns each, and the `*_prefs` arrays) are transcribed row by row, with the
literal texts of the C source as the Rust literals (so the doubles are the same), in the
order of `BlastLoadMatrixValues`. BLOSUM62_20 is left out: blast_stat.c compiles it only
under BLOSUM62_20_ENABLE, which the build does not define.

Usage: gen_protein_tables.py --ncbi-src C++DIR [--check]
  --check: exit 1 when the committed file differs from what would be generated.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TARGET = REPO / "LOSAT/src/stats/protein_tables.rs"
# BlastLoadMatrixValues (blast_stat.c:2952-2992), IDENTITY only when !standard_only.
ORDER = [("BLOSUM80", "blosum80"), ("BLOSUM62", "blosum62"), ("BLOSUM50", "blosum50"), ("BLOSUM45", "blosum45"),
         ("PAM250", "pam250"), ("BLOSUM90", "blosum90"), ("PAM30", "pam30"), ("PAM70", "pam70"),
         ("IDENTITY", "prot_idenity")]
PREFS = {"prot_idenity": "prot_identity"}


def literal(text: str) -> str:
    text = text.strip()
    if text == "(double) INT2_MAX":
        return "32767.0"
    if re.fullmatch(r"-?\d+", text):
        return text + ".0"
    if re.fullmatch(r"-?\d+\.", text):
        return text + "0"
    if re.fullmatch(r"-?\d*\.\d+", text):
        return text if not text.startswith((".", "-.")) else text.replace(".", "0.", 1)
    raise SystemExit(f"unexpected literal {text!r}")


def generate(src: Path) -> str:
    path = src / "src/algo/blast/core/blast_stat.c"
    lines = path.read_text().splitlines()
    text = "\n".join(lines)
    out = [
        "//! NCBI's gapped Karlin-Altschul and Gumbel tables of the protein matrices, generated by",
        "//! docs/evidence/losat_web_e2e/gen_protein_tables.py from",
        "//! c++/src/algo/blast/core/blast_stat.c (598d8ae6); do not edit by hand.",
        "//!",
        "//! Each row is NCBI's `array_of_8` row (gap open, gap extend, decline-to-align, Lambda,",
        "//! K, H, alpha, beta, C, alpha_v, sigma) with the C literals as written; INT2_MAX is",
        "//! 32767. The tables are in the order of `BlastLoadMatrixValues`.",
        "",
        "/// One row of a matrix's table (NCBI `array_of_8`).",
        "#[derive(Debug, Clone, Copy, PartialEq)]",
        "pub struct ProteinTableRow(pub [f64; 11]);",
        "",
        "/// A matrix's table and its preference flags (NCBI `MatrixInfo`).",
        "#[derive(Debug)]",
        "pub struct ProteinMatrixTable {",
        "    pub name: &'static str,",
        "    pub values: &'static [ProteinTableRow],",
        "    pub prefs: &'static [i32],",
        "}",
        "",
    ]
    names = []
    for name, cname in ORDER:
        start = next(i for i, line in enumerate(lines) if re.match(rf"static array_of_8 {cname}_values\[", line))
        end = next(i for i in range(start, len(lines)) if lines[i].startswith("}"))
        body = "\n".join(lines[start + 1:end])
        rows = re.findall(r"\{([^{}]*)\}", body)
        pname = PREFS.get(cname, cname)
        pstart = next(i for i, line in enumerate(lines) if re.match(rf"static Int4 {pname}_prefs\[", line))
        pend = next(i for i in range(pstart, len(lines)) if lines[i].startswith("}"))
        prefs = re.findall(r"BLAST_MATRIX_(NOMINAL|PREFERRED|BEST)", "\n".join(lines[pstart + 1:pend]))
        if len(prefs) != len(rows):
            raise SystemExit(f"{cname}: {len(rows)} rows, {len(prefs)} prefs")
        const = name.replace("IDENTITY", "IDENTITY")
        out.append(f"/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:{start + 1}-{end + 1}")
        out.append("/// ```c")
        out.append(f"/// {lines[start]}")
        out.append(f"/// {lines[start + 1].strip()}")
        out.append("/// ...")
        out.append("/// ```")
        out.append(f"const {const}_VALUES: [ProteinTableRow; {len(rows)}] = [")
        for row in rows:
            fields = [literal(field) for field in row.split(",")]
            if len(fields) != 11:
                raise SystemExit(f"{cname}: row with {len(fields)} fields")
            out.append(f"    ProteinTableRow([{', '.join(fields)}]),")
        out.append("];")
        out.append("")
        values = {"NOMINAL": 0, "PREFERRED": 1, "BEST": 2}
        out.append(f"/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:{pstart + 1}-{pend + 1}")
        out.append("/// ```c")
        out.append(f"/// {lines[pstart]}")
        out.append(f"/// {lines[pstart + 1].strip()}")
        out.append("/// ...")
        out.append("/// ```")
        out.append(f"const {const}_PREFS: [i32; {len(prefs)}] = [{', '.join(str(values[p]) for p in prefs)}];")
        out.append("")
        names.append((name, const))
    load = next(i for i, line in enumerate(lines) if line.startswith("BlastLoadMatrixValues (Boolean standard_only)"))
    load_end = next(i for i in range(load, len(lines)) if lines[i].startswith("}"))
    out.append(f"/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:{load + 1}-{load_end + 1}")
    out.append("/// ```c")
    for i in range(load, load + 9):
        out.append(f"/// {lines[i]}".rstrip())
    out.append("/// ...")
    out.append("/// ```")
    out.append("/// The last table (IDENTITY) is left out when `standard_only` is set.")
    out.append(f"pub static PROTEIN_MATRIX_TABLES: [ProteinMatrixTable; {len(names)}] = [")
    for name, const in names:
        out.append(f"    ProteinMatrixTable {{ name: \"{name}\", values: &{const}_VALUES, prefs: &{const}_PREFS }},")
    out.append("];")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ncbi-src", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = subprocess.run(["rustfmt", "+1.92.0", "--edition", "2021", "--emit", "stdout", "--quiet"],
                          input=generate(args.ncbi_src), capture_output=True, text=True, check=True).stdout
    if args.check:
        return 0 if TARGET.read_text() == text else 1
    TARGET.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
