//! NCBI's gapped Karlin-Altschul and Gumbel tables of the protein matrices, generated by
//! docs/evidence/losat_web_e2e/gen_protein_tables.py from
//! c++/src/algo/blast/core/blast_stat.c (598d8ae6); do not edit by hand.
//!
//! Each row is NCBI's `array_of_8` row (gap open, gap extend, decline-to-align, Lambda,
//! K, H, alpha, beta, C, alpha_v, sigma) with the C literals as written; INT2_MAX is
//! 32767. The tables are in the order of `BlastLoadMatrixValues`.

/// One row of a matrix's table (NCBI `array_of_8`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ProteinTableRow(pub [f64; 11]);

/// A matrix's table and its preference flags (NCBI `MatrixInfo`).
#[derive(Debug)]
pub struct ProteinMatrixTable {
    pub name: &'static str,
    pub values: &'static [ProteinTableRow],
    pub prefs: &'static [i32],
}

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:290-301
/// ```c
/// static array_of_8 blosum80_values[BLOSUM80_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.3430, 0.177, 0.6568, 0.5222, -1.6, 0.564057, 1.918130, 1.918130},
/// ...
/// ```
const BLOSUM80_VALUES: [ProteinTableRow; 10] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.3430, 0.177, 0.6568, 0.5222, -1.6, 0.564057, 1.918130,
        1.918130,
    ]),
    ProteinTableRow([
        25.0, 2.0, 32767.0, 0.342, 0.17, 0.66, 0.52, -1.6, 0.563956, 1.731000, 1.731300,
    ]),
    ProteinTableRow([
        13.0, 2.0, 32767.0, 0.336, 0.15, 0.57, 0.59, -3.0, 0.570979, 2.673470, 2.692300,
    ]),
    ProteinTableRow([
        9.0, 2.0, 32767.0, 0.319, 0.11, 0.42, 0.76, -6.0, 0.587837, 5.576090, 5.667860,
    ]),
    ProteinTableRow([
        8.0, 2.0, 32767.0, 0.308, 0.090, 0.35, 0.89, -9.0, 0.597556, 7.536950, 7.686230,
    ]),
    ProteinTableRow([
        7.0, 2.0, 32767.0, 0.293, 0.070, 0.27, 1.1, -14.0, 0.615254, 11.586600, 11.840400,
    ]),
    ProteinTableRow([
        6.0, 2.0, 32767.0, 0.268, 0.045, 0.19, 1.4, -19.0, 0.644054, 19.958100, 20.441200,
    ]),
    ProteinTableRow([
        11.0, 1.0, 32767.0, 0.314, 0.095, 0.35, 0.90, -9.0, 0.590702, 8.808610, 9.223320,
    ]),
    ProteinTableRow([
        10.0, 1.0, 32767.0, 0.299, 0.071, 0.27, 1.1, -14.0, 0.609620, 13.833800, 14.533400,
    ]),
    ProteinTableRow([
        9.0, 1.0, 32767.0, 0.279, 0.048, 0.20, 1.4, -19.0, 0.623800, 24.252000, 25.490400,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:303-314
/// ```c
/// static Int4 blosum80_prefs[BLOSUM80_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const BLOSUM80_PREFS: [i32; 10] = [0, 0, 0, 0, 0, 0, 0, 0, 2, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:258-271
/// ```c
/// static array_of_8 blosum62_values[BLOSUM62_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.3176, 0.134, 0.4012, 0.7916, -3.2, 0.623757, 4.964660, 4.964660},
/// ...
/// ```
const BLOSUM62_VALUES: [ProteinTableRow; 12] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.3176, 0.134, 0.4012, 0.7916, -3.2, 0.623757, 4.964660,
        4.964660,
    ]),
    ProteinTableRow([
        11.0, 2.0, 32767.0, 0.297, 0.082, 0.27, 1.1, -10.0, 0.641766, 12.673800, 12.757600,
    ]),
    ProteinTableRow([
        10.0, 2.0, 32767.0, 0.291, 0.075, 0.23, 1.3, -15.0, 0.649362, 16.474000, 16.602600,
    ]),
    ProteinTableRow([
        9.0, 2.0, 32767.0, 0.279, 0.058, 0.19, 1.5, -19.0, 0.659245, 22.751900, 22.950000,
    ]),
    ProteinTableRow([
        8.0, 2.0, 32767.0, 0.264, 0.045, 0.15, 1.8, -26.0, 0.672692, 35.483800, 35.821300,
    ]),
    ProteinTableRow([
        7.0, 2.0, 32767.0, 0.239, 0.027, 0.10, 2.5, -46.0, 0.702056, 61.238300, 61.886000,
    ]),
    ProteinTableRow([
        6.0, 2.0, 32767.0, 0.201, 0.012, 0.061, 3.3, -58.0, 0.740802, 140.417000, 141.882000,
    ]),
    ProteinTableRow([
        13.0, 1.0, 32767.0, 0.292, 0.071, 0.23, 1.2, -11.0, 0.647715, 19.506300, 19.893100,
    ]),
    ProteinTableRow([
        12.0, 1.0, 32767.0, 0.283, 0.059, 0.19, 1.5, -19.0, 0.656391, 27.856200, 28.469900,
    ]),
    ProteinTableRow([
        11.0, 1.0, 32767.0, 0.267, 0.041, 0.14, 1.9, -30.0, 0.669720, 42.602800, 43.636200,
    ]),
    ProteinTableRow([
        10.0, 1.0, 32767.0, 0.243, 0.024, 0.10, 2.5, -44.0, 0.693267, 83.178700, 85.065600,
    ]),
    ProteinTableRow([
        9.0, 1.0, 32767.0, 0.206, 0.010, 0.052, 4.0, -87.0, 0.731887, 210.333000, 214.842000,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:273-286
/// ```c
/// static Int4 blosum62_prefs[BLOSUM62_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const BLOSUM62_PREFS: [i32; 12] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:219-236
/// ```c
/// static array_of_8 blosum50_values[BLOSUM50_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.2318, 0.112, 0.3362, 0.6895, -4.0, 0.609639, 5.388310, 5.388310},
/// ...
/// ```
const BLOSUM50_VALUES: [ProteinTableRow; 16] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.2318, 0.112, 0.3362, 0.6895, -4.0, 0.609639, 5.388310,
        5.388310,
    ]),
    ProteinTableRow([
        13.0, 3.0, 32767.0, 0.212, 0.063, 0.19, 1.1, -16.0, 0.639287, 18.113800, 18.202800,
    ]),
    ProteinTableRow([
        12.0, 3.0, 32767.0, 0.206, 0.055, 0.17, 1.2, -18.0, 0.644715, 22.654600, 22.777700,
    ]),
    ProteinTableRow([
        11.0, 3.0, 32767.0, 0.197, 0.042, 0.14, 1.4, -25.0, 0.656327, 29.861100, 30.045700,
    ]),
    ProteinTableRow([
        10.0, 3.0, 32767.0, 0.186, 0.031, 0.11, 1.7, -34.0, 0.671150, 42.393800, 42.674000,
    ]),
    ProteinTableRow([
        9.0, 3.0, 32767.0, 0.172, 0.022, 0.082, 2.1, -48.0, 0.694326, 66.069600, 66.516400,
    ]),
    ProteinTableRow([
        16.0, 2.0, 32767.0, 0.215, 0.066, 0.20, 1.05, -15.0, 0.633899, 17.951800, 18.092100,
    ]),
    ProteinTableRow([
        15.0, 2.0, 32767.0, 0.210, 0.058, 0.17, 1.2, -20.0, 0.641985, 21.940100, 22.141800,
    ]),
    ProteinTableRow([
        14.0, 2.0, 32767.0, 0.202, 0.045, 0.14, 1.4, -27.0, 0.650682, 28.681200, 28.961900,
    ]),
    ProteinTableRow([
        13.0, 2.0, 32767.0, 0.193, 0.035, 0.12, 1.6, -32.0, 0.660984, 42.059500, 42.471600,
    ]),
    ProteinTableRow([
        12.0, 2.0, 32767.0, 0.181, 0.025, 0.095, 1.9, -41.0, 0.678090, 63.747600, 64.397300,
    ]),
    ProteinTableRow([
        19.0, 1.0, 32767.0, 0.212, 0.057, 0.18, 1.2, -21.0, 0.635714, 26.311200, 26.923300,
    ]),
    ProteinTableRow([
        18.0, 1.0, 32767.0, 0.207, 0.050, 0.15, 1.4, -28.0, 0.643523, 34.903700, 35.734800,
    ]),
    ProteinTableRow([
        17.0, 1.0, 32767.0, 0.198, 0.037, 0.12, 1.6, -33.0, 0.654504, 48.895800, 50.148600,
    ]),
    ProteinTableRow([
        16.0, 1.0, 32767.0, 0.186, 0.025, 0.10, 1.9, -42.0, 0.667750, 76.469100, 78.443000,
    ]),
    ProteinTableRow([
        15.0, 1.0, 32767.0, 0.171, 0.015, 0.063, 2.7, -76.0, 0.694575, 140.053000, 144.160000,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:238-255
/// ```c
/// static Int4 blosum50_prefs[BLOSUM50_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const BLOSUM50_PREFS: [i32; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:183-198
/// ```c
/// static array_of_8 blosum45_values[BLOSUM45_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.2291, 0.0924, 0.2514, 0.9113, -5.7, 0.641318, 9.611060, 9.611060},
/// ...
/// ```
const BLOSUM45_VALUES: [ProteinTableRow; 14] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.2291, 0.0924, 0.2514, 0.9113, -5.7, 0.641318, 9.611060,
        9.611060,
    ]),
    ProteinTableRow([
        13.0, 3.0, 32767.0, 0.207, 0.049, 0.14, 1.5, -22.0, 0.671128, 35.855900, 35.963900,
    ]),
    ProteinTableRow([
        12.0, 3.0, 32767.0, 0.199, 0.039, 0.11, 1.8, -34.0, 0.691530, 45.693600, 45.851700,
    ]),
    ProteinTableRow([
        11.0, 3.0, 32767.0, 0.190, 0.031, 0.095, 2.0, -38.0, 0.691181, 62.874100, 63.103700,
    ]),
    ProteinTableRow([
        10.0, 3.0, 32767.0, 0.179, 0.023, 0.075, 2.4, -51.0, 0.710529, 88.286800, 88.639100,
    ]),
    ProteinTableRow([
        16.0, 2.0, 32767.0, 0.210, 0.051, 0.14, 1.5, -24.0, 0.666680, 36.279800, 36.452400,
    ]),
    ProteinTableRow([
        15.0, 2.0, 32767.0, 0.203, 0.041, 0.12, 1.7, -31.0, 0.673871, 44.825700, 45.060400,
    ]),
    ProteinTableRow([
        14.0, 2.0, 32767.0, 0.195, 0.032, 0.10, 1.9, -36.0, 0.685753, 60.736200, 61.102300,
    ]),
    ProteinTableRow([
        13.0, 2.0, 32767.0, 0.185, 0.024, 0.084, 2.2, -45.0, 0.698480, 85.148100, 85.689400,
    ]),
    ProteinTableRow([
        12.0, 2.0, 32767.0, 0.171, 0.016, 0.061, 2.8, -65.0, 0.713429, 127.758000, 128.582000,
    ]),
    ProteinTableRow([
        19.0, 1.0, 32767.0, 0.205, 0.040, 0.11, 1.9, -43.0, 0.672302, 53.071400, 53.828200,
    ]),
    ProteinTableRow([
        18.0, 1.0, 32767.0, 0.198, 0.032, 0.10, 2.0, -43.0, 0.682580, 72.342400, 73.403900,
    ]),
    ProteinTableRow([
        17.0, 1.0, 32767.0, 0.189, 0.024, 0.079, 2.4, -57.0, 0.695035, 103.055000, 104.721000,
    ]),
    ProteinTableRow([
        16.0, 1.0, 32767.0, 0.176, 0.016, 0.063, 2.8, -67.0, 0.712966, 170.100000, 173.003000,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:200-215
/// ```c
/// static Int4 blosum45_prefs[BLOSUM45_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const BLOSUM45_PREFS: [i32; 14] = [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:340-357
/// ```c
/// static array_of_8 pam250_values[PAM250_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.2252, 0.0868, 0.2223, 0.98, -5.0, 0.660059, 11.754300, 11.754300},
/// ...
/// ```
const PAM250_VALUES: [ProteinTableRow; 16] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.2252, 0.0868, 0.2223, 0.98, -5.0, 0.660059, 11.754300,
        11.754300,
    ]),
    ProteinTableRow([
        15.0, 3.0, 32767.0, 0.205, 0.049, 0.13, 1.6, -23.0, 0.687656, 34.578400, 34.928000,
    ]),
    ProteinTableRow([
        14.0, 3.0, 32767.0, 0.200, 0.043, 0.12, 1.7, -26.0, 0.689768, 43.353000, 43.443800,
    ]),
    ProteinTableRow([
        13.0, 3.0, 32767.0, 0.194, 0.036, 0.10, 1.9, -31.0, 0.697431, 50.948500, 51.081700,
    ]),
    ProteinTableRow([
        12.0, 3.0, 32767.0, 0.186, 0.029, 0.085, 2.2, -41.0, 0.704565, 69.606500, 69.793600,
    ]),
    ProteinTableRow([
        11.0, 3.0, 32767.0, 0.174, 0.020, 0.070, 2.5, -48.0, 0.722438, 98.653500, 98.927100,
    ]),
    ProteinTableRow([
        17.0, 2.0, 32767.0, 0.204, 0.047, 0.12, 1.7, -28.0, 0.684799, 41.583800, 41.735800,
    ]),
    ProteinTableRow([
        16.0, 2.0, 32767.0, 0.198, 0.038, 0.11, 1.8, -29.0, 0.691098, 51.635200, 51.843900,
    ]),
    ProteinTableRow([
        15.0, 2.0, 32767.0, 0.191, 0.031, 0.087, 2.2, -44.0, 0.699051, 67.256700, 67.558500,
    ]),
    ProteinTableRow([
        14.0, 2.0, 32767.0, 0.182, 0.024, 0.073, 2.5, -53.0, 0.714103, 96.315100, 96.756800,
    ]),
    ProteinTableRow([
        13.0, 2.0, 32767.0, 0.171, 0.017, 0.059, 2.9, -64.0, 0.728738, 135.653000, 136.339000,
    ]),
    ProteinTableRow([
        21.0, 1.0, 32767.0, 0.205, 0.045, 0.11, 1.8, -34.0, 0.683265, 48.728200, 49.218800,
    ]),
    ProteinTableRow([
        20.0, 1.0, 32767.0, 0.199, 0.037, 0.10, 1.9, -35.0, 0.689380, 60.832000, 61.514100,
    ]),
    ProteinTableRow([
        19.0, 1.0, 32767.0, 0.192, 0.029, 0.083, 2.3, -52.0, 0.696344, 84.019700, 84.985600,
    ]),
    ProteinTableRow([
        18.0, 1.0, 32767.0, 0.183, 0.021, 0.070, 2.6, -60.0, 0.710525, 113.829000, 115.184000,
    ]),
    ProteinTableRow([
        17.0, 1.0, 32767.0, 0.171, 0.014, 0.052, 3.3, -86.0, 0.727000, 175.071000, 177.196000,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:359-376
/// ```c
/// static Int4 pam250_prefs[PAM250_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const PAM250_PREFS: [i32; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:317-326
/// ```c
/// static array_of_8 blosum90_values[BLOSUM90_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.3346, 0.190, 0.7547, 0.4434, -1.4 , 0.544178, 1.377760, 1.377760},
/// ...
/// ```
const BLOSUM90_VALUES: [ProteinTableRow; 8] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.3346, 0.190, 0.7547, 0.4434, -1.4, 0.544178, 1.377760,
        1.377760,
    ]),
    ProteinTableRow([
        9.0, 2.0, 32767.0, 0.310, 0.12, 0.46, 0.67, -6.0, 0.570267, 4.232290, 4.334170,
    ]),
    ProteinTableRow([
        8.0, 2.0, 32767.0, 0.300, 0.099, 0.39, 0.76, -7.0, 0.581580, 5.797020, 5.961420,
    ]),
    ProteinTableRow([
        7.0, 2.0, 32767.0, 0.283, 0.072, 0.30, 0.93, -11.0, 0.600024, 9.040880, 9.321600,
    ]),
    ProteinTableRow([
        6.0, 2.0, 32767.0, 0.259, 0.048, 0.22, 1.2, -16.0, 0.629344, 16.024400, 16.531600,
    ]),
    ProteinTableRow([
        11.0, 1.0, 32767.0, 0.302, 0.093, 0.39, 0.78, -8.0, 0.576919, 7.143250, 7.619190,
    ]),
    ProteinTableRow([
        10.0, 1.0, 32767.0, 0.290, 0.075, 0.28, 1.04, -15.0, 0.591366, 11.483900, 12.269800,
    ]),
    ProteinTableRow([
        9.0, 1.0, 32767.0, 0.265, 0.044, 0.20, 1.3, -19.0, 0.613013, 21.408300, 22.840900,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:328-337
/// ```c
/// static Int4 blosum90_prefs[BLOSUM90_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const BLOSUM90_PREFS: [i32; 8] = [0, 0, 0, 0, 0, 0, 2, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:379-391
/// ```c
/// static array_of_8 pam30_values[PAM30_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.3400, 0.283, 1.754, 0.1938, -0.3, 0.436164, 0.161818, 0.161818},
/// ...
/// ```
const PAM30_VALUES: [ProteinTableRow; 11] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.3400, 0.283, 1.754, 0.1938, -0.3, 0.436164, 0.161818, 0.161818,
    ]),
    ProteinTableRow([
        7.0, 2.0, 32767.0, 0.305, 0.15, 0.87, 0.35, -3.0, 0.479087, 1.014010, 1.162730,
    ]),
    ProteinTableRow([
        6.0, 2.0, 32767.0, 0.287, 0.11, 0.68, 0.42, -4.0, 0.499980, 1.688060, 1.951430,
    ]),
    ProteinTableRow([
        5.0, 2.0, 32767.0, 0.264, 0.079, 0.45, 0.59, -7.0, 0.533009, 3.377010, 3.871950,
    ]),
    ProteinTableRow([
        10.0, 1.0, 32767.0, 0.309, 0.15, 0.88, 0.35, -3.0, 0.474741, 1.372050, 1.788770,
    ]),
    ProteinTableRow([
        9.0, 1.0, 32767.0, 0.294, 0.11, 0.61, 0.48, -6.0, 0.492716, 2.463920, 3.186150,
    ]),
    ProteinTableRow([
        8.0, 1.0, 32767.0, 0.270, 0.072, 0.40, 0.68, -10.0, 0.521286, 5.368130, 6.763480,
    ]),
    ProteinTableRow([
        15.0, 3.0, 32767.0, 0.339, 0.28, 1.70, 0.20, -0.5, 0.437688, 0.157089, 0.155299,
    ]),
    ProteinTableRow([
        14.0, 2.0, 32767.0, 0.337, 0.27, 1.62, 0.21, -0.8, 0.440010, 0.206970, 0.198524,
    ]),
    ProteinTableRow([
        14.0, 1.0, 32767.0, 0.333, 0.27, 1.43, 0.23, -1.4, 0.444817, 0.436301, 0.361947,
    ]),
    ProteinTableRow([
        13.0, 3.0, 32767.0, 0.338, 0.27, 1.69, 0.20, -0.5, 0.439086, 0.178973, 0.175436,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:393-405
/// ```c
/// static Int4 pam30_prefs[PAM30_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const PAM30_PREFS: [i32; 11] = [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:409-419
/// ```c
/// static array_of_8 pam70_values[PAM70_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.3345, 0.229, 1.029, 0.3250,   -0.7, 0.511296, 0.633439, 0.633439},
/// ...
/// ```
const PAM70_VALUES: [ProteinTableRow; 9] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.3345, 0.229, 1.029, 0.3250, -0.7, 0.511296, 0.633439, 0.633439,
    ]),
    ProteinTableRow([
        8.0, 2.0, 32767.0, 0.301, 0.12, 0.54, 0.56, -5.0, 0.549019, 2.881650, 3.025710,
    ]),
    ProteinTableRow([
        7.0, 2.0, 32767.0, 0.286, 0.093, 0.43, 0.67, -7.0, 0.565659, 4.534540, 4.785780,
    ]),
    ProteinTableRow([
        6.0, 2.0, 32767.0, 0.264, 0.064, 0.29, 0.90, -12.0, 0.596330, 7.942630, 8.402720,
    ]),
    ProteinTableRow([
        11.0, 1.0, 32767.0, 0.305, 0.12, 0.52, 0.59, -6.0, 0.543514, 3.681400, 4.108020,
    ]),
    ProteinTableRow([
        10.0, 1.0, 32767.0, 0.291, 0.091, 0.41, 0.71, -9.0, 0.560723, 6.002970, 6.716570,
    ]),
    ProteinTableRow([
        9.0, 1.0, 32767.0, 0.270, 0.060, 0.28, 0.97, -14.0, 0.585186, 11.360800, 12.636700,
    ]),
    ProteinTableRow([
        11.0, 2.0, 32767.0, 0.323, 0.186, 0.80, 1.32, -27.0, 0.524062, 1.321301, 1.281671,
    ]),
    ProteinTableRow([
        12.0, 3.0, 32767.0, 0.330, 0.219, 0.93, 0.82, -16.0, 0.516845, 0.818768, 0.811240,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:421-431
/// ```c
/// static Int4 pam70_prefs[PAM70_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const PAM70_PREFS: [i32; 9] = [0, 0, 0, 0, 0, 2, 0, 0, 0];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:578-581
/// ```c
/// static array_of_8 prot_idenity_values[PROT_IDENTITY_VALUES_MAX] = {
/// {(double) INT2_MAX, (double) INT2_MAX, (double) INT2_MAX, 0.28768, 0.282, 1.69, 0.1703, -0.3, 0.43828, 0.16804, 0.16804},
/// ...
/// ```
const IDENTITY_VALUES: [ProteinTableRow; 2] = [
    ProteinTableRow([
        32767.0, 32767.0, 32767.0, 0.28768, 0.282, 1.69, 0.1703, -0.3, 0.43828, 0.16804, 0.16804,
    ]),
    ProteinTableRow([
        15.0, 2.0, 32767.0, 0.2835, 0.255, 1.49, 0.19, -1.0, 0.44502, 0.24613, 0.22743,
    ]),
];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:583-586
/// ```c
/// static Int4 prot_identity_prefs[PROT_IDENTITY_VALUES_MAX] = {
/// BLAST_MATRIX_NOMINAL,
/// ...
/// ```
const IDENTITY_PREFS: [i32; 2] = [0, 2];

/// NCBI reference: c++/src/algo/blast/core/blast_stat.c:2952-2995
/// ```c
/// BlastLoadMatrixValues (Boolean standard_only)
///
/// {
///    MatrixInfo* matrix_info;
///    ListNode* retval=NULL;
///
///    matrix_info = MatrixInfoNew("BLOSUM80", blosum80_values, blosum80_prefs, BLOSUM80_VALUES_MAX);
///    ListNodeAddPointer(&retval, 0, matrix_info);
///
/// ...
/// ```
/// The last table (IDENTITY) is left out when `standard_only` is set.
pub static PROTEIN_MATRIX_TABLES: [ProteinMatrixTable; 9] = [
    ProteinMatrixTable {
        name: "BLOSUM80",
        values: &BLOSUM80_VALUES,
        prefs: &BLOSUM80_PREFS,
    },
    ProteinMatrixTable {
        name: "BLOSUM62",
        values: &BLOSUM62_VALUES,
        prefs: &BLOSUM62_PREFS,
    },
    ProteinMatrixTable {
        name: "BLOSUM50",
        values: &BLOSUM50_VALUES,
        prefs: &BLOSUM50_PREFS,
    },
    ProteinMatrixTable {
        name: "BLOSUM45",
        values: &BLOSUM45_VALUES,
        prefs: &BLOSUM45_PREFS,
    },
    ProteinMatrixTable {
        name: "PAM250",
        values: &PAM250_VALUES,
        prefs: &PAM250_PREFS,
    },
    ProteinMatrixTable {
        name: "BLOSUM90",
        values: &BLOSUM90_VALUES,
        prefs: &BLOSUM90_PREFS,
    },
    ProteinMatrixTable {
        name: "PAM30",
        values: &PAM30_VALUES,
        prefs: &PAM30_PREFS,
    },
    ProteinMatrixTable {
        name: "PAM70",
        values: &PAM70_VALUES,
        prefs: &PAM70_PREFS,
    },
    ProteinMatrixTable {
        name: "IDENTITY",
        values: &IDENTITY_VALUES,
        prefs: &IDENTITY_PREFS,
    },
];
